# fly.toml file for frontend
app = "trello-frontend"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[env]
  NEXT_PUBLIC_GRAPHQL_ENDPOINT = "https://trello-backend.fly.dev/graphql"
  NODE_ENV = "production"
  BACKEND_URL = "https://trello-backend.fly.dev"