default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DB_HOST"] || "localhost" %>
  username: <%= ENV["DB_USERNAME"] || "postgres" %>
  password: <%= ENV["DB_PASSWORD"] || "postgres" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trello_clone_dev

test:
  <<: *default
  database: trello_clone_test

production:
  <<: *default
  database: <%= ENV["DB_NAME"] || "trello_clone_production" %>
  url: <%= ENV["DATABASE_URL"] %>