# fly.toml file for PostgreSQL database
app = "trello-db"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = 5
processes = ["postgres"]

[build]
  image = "flyio/postgres:15"

[env]
  PRIMARY_REGION = "ams"

[experimental]
  cmd = ["/srv/startup.sh", "postgres"]
  entrypoint = ["tini", "--", "/docker-entrypoint.sh"]

[[mounts]]
  source = "data"
  destination = "/data"

[metrics]
  port = 9187
  path = "/metrics"

[[services]]
  internal_port = 5555
  protocol = "tcp"
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

  [[services.ports]]
    port = "5432"
    handlers = ["pg_tls"]
    tls_options = { alpn = ["h2", "http/1.1"], versions = ["TLSv1.2", "TLSv1.3"] }

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    port = "5432"