[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
startretries=3

[program:rails]
command=bash -c "cd /app/backend && bin/rails db:prepare && bin/rails server -b 0.0.0.0 -p 3000"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
startretries=3
user=rails
environment=RAILS_ENV=production,BUNDLE_PATH="/usr/local/bundle"

[program:nextjs]
command=bash -c "cd /app/frontend/standalone && PORT=3001 node server.js"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
startretries=3
user=rails
environment=NODE_ENV=production,PORT=3001
